apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-idle-app
  labels:
    app: java-idle
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: java-idle
  template:
    metadata:
      labels:
        app: java-idle
    spec:
      containers:
      - name: java-container
        image: java-idle-image:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        startupProbe:
          httpGet:
            path: /
            port: 8080
          failureThreshold: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          limits:
            cpu: "200m"
            memory: "384Mi"
          requests:
            cpu: "100m"
            memory: "384Mi"
